export const IF_NOTIFICATIONS_REQUEST = 'IF_NOTIFICATIONS_REQUEST'
export const IF_NOTIFICATIONS_SUCCESS = 'IF_NOTIFICATIONS_SUCCESS'
export const IF_NOTIFICATIONS_FAIL = 'IF_NOTIFICATIONS_FAIL'

export const SEE_NOTIFICATIONS_REQUEST = 'SEE_NOTIFICATIONS_REQUEST'
export const SEE_NOTIFICATIONS_SUCCESS = 'SEE_NOTIFICATIONS_SUCCESS'
export const SEE_NOTIFICATIONS_FAIL = 'SEE_NOTIFICATIONS_FAIL'

export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL'
