export const PLACE_AUTOCOMPLETE_REQUEST = 'PLACE_AUTOCOMPLETE_REQUEST'
export const PLACE_AUTOCOMPLETE_SUCCESS = 'PLACE_AUTOCOMPLETE_SUCCESS'
export const PLACE_AUTOCOMPLETE_FAIL = 'PLACE_AUTOCOMPLETE_FAIL'

export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'
