export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST'
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS'
export const SERVICE_LIST_FAIL = 'SERVICE_LIST_FAIL'
export const SERVICE_LIST_RESET = 'SERVICE_LIST_RESET'

export const SERVICE_GET_CATEGORIES_REQUEST = 'SERVICE_GET_CATEGORIES_REQUEST'
export const SERVICE_GET_CATEGORIES_SUCCESS = 'SERVICE_GET_CATEGORIES_SUCCESS'
export const SERVICE_GET_CATEGORIES_FAIL = 'SERVICE_GET_CATEGORIES_FAIL'

export const SERVICE_PROFILE_REQUEST = 'SERVICE_PROFILE_REQUEST'
export const SERVICE_PROFILE_SUCCESS = 'SERVICE_PROFILE_SUCCESS'
export const SERVICE_PROFILE_FAIL = 'SERVICE_PROFILE_FAIL'

export const SERVICE_NEW_CATEGORY_REQUEST = 'SERVICE_NEW_CATEGORY_REQUEST'
export const SERVICE_NEW_CATEGORY_SUCCESS = 'SERVICE_NEW_CATEGORY_SUCCESS'
export const SERVICE_NEW_CATEGORY_FAIL = 'SERVICE_NEW_CATEGORY_FAIL'

export const SERVICE_CREATE_REQUEST = 'SERVICE_CREATE_REQUEST'
export const SERVICE_CREATE_SUCCESS = 'SERVICE_CREATE_SUCCESS'
export const SERVICE_CREATE_FAIL = 'SERVICE_CREATE_FAIL'
export const SERVICE_CREATE_RESET = 'SERVICE_CREATE_RESET'

export const SERVICE_RECOMMEND_REQUEST = 'SERVICE_RECOMMEND_REQUEST'
export const SERVICE_RECOMMEND_SUCCESS = 'SERVICE_RECOMMEND_SUCCESS'
export const SERVICE_RECOMMEND_FAIL = 'SERVICE_RECOMMEND_FAIL'
export const SERVICE_RECOMMEND_RESET = 'SERVICE_RECOMMEND_RESET'

export const SERVICE_EDIT_PROFILE_REQUEST = 'SERVICE_EDIT_PROFILE_REQUEST'
export const SERVICE_EDIT_PROFILE_SUCCESS = 'SERVICE_EDIT_PROFILE_SUCCESS'
export const SERVICE_EDIT_PROFILE_FAIL = 'SERVICE_EDIT_PROFILE_FAIL'
export const SERVICE_EDIT_PROFILE_RESET = 'SERVICE_EDIT_PROFILE_RESET'
